/* =====================================================
   ÍNDICE DAS CONSTANTES DO SISTEMA
   Mantém as constantes acessíveis em um único objeto global
   sem alterar o comportamento dos scripts atuais.
===================================================== */

window.APP_CONSTANTS = Object.freeze({
  ANDARES_MANUTENCAO,
  LOCAIS_PRIMEIRO_ANDAR_MANUTENCAO,
  LOCAIS_POR_ANDAR_MANUTENCAO,
  CATEGORIAS_MANUTENCAO,
  SUBCATEGORIAS_MANUTENCAO,
  STATUS_OS,
  STATUS_OS_LISTA,
  PRIORIDADES_OS,
  PRIORIDADES_OS_LISTA,
  TIPOS_MANUTENCAO,
  TIPOS_MANUTENCAO_LISTA,
  PERFIS_USUARIO,
  PERFIS_USUARIO_LISTA,
  NOMES_PERFIS_USUARIO,
  PERMISSOES_APP,
  PERMISSOES_POR_PERFIL,
  COLLECTIONS,
  STATUS_EXPORTACAO_OS,
  STATUS_EXPORTACAO_OS_FINALIZADAS,
  COLUNAS_EXPORTACAO_OS,
  COLUNAS_EXPORTACAO_OS_FINALIZADAS
});
