/* =====================================================
   PERMISSÕES DO SISTEMA
   Centraliza o que cada perfil pode visualizar ou executar.
===================================================== */

const PERMISSOES_APP = Object.freeze({
  ACESSAR_APP: "acessarApp",
  ABRIR_OS: "abrirOS",
  VER_MINHAS_OS: "verMinhasOS",
  VER_TODAS_OS: "verTodasOS",
  CANCELAR_PROPRIA_OS: "cancelarPropriaOS",
  ASSUMIR_ATENDIMENTO: "assumirAtendimento",
  ALTERAR_STATUS_OS: "alterarStatusOS",
  ALTERAR_PRIORIDADE_OS: "alterarPrioridadeOS",
  FINALIZAR_OS: "finalizarOS",
  VER_PAINEL: "verPainel",
  VER_COMUNICADOS: "verComunicados",
  CRIAR_COMUNICADO: "criarComunicado",
  VER_NOTIFICACOES: "verNotificacoes",
  VER_NOTIFICACOES_PROPRIAS: "verNotificacoesProprias",
  VER_PERFIL: "verPerfil",
  VER_ATIVOS: "verAtivos",
  GERENCIAR_ATIVOS: "gerenciarAtivos",
  VER_PREVENTIVAS: "verPreventivas",
  GERENCIAR_PREVENTIVAS: "gerenciarPreventivas",
  VER_DIAGNOSTICO: "verDiagnostico",
  GERENCIAR_DIAGNOSTICO: "gerenciarDiagnostico",
  EXPORTAR_DADOS: "exportarDados",
  VER_LOGS_TECNICOS: "verLogsTecnicos",
  GERENCIAR_USUARIOS: "gerenciarUsuarios",
  AJUSTAR_CONFIGURACOES: "ajustarConfiguracoes",
  AUDITAR_HISTORICO: "auditarHistorico"
});

const PERMISSOES_POR_PERFIL = Object.freeze({
  [PERFIS_USUARIO.COLABORADOR]: Object.freeze([
    PERMISSOES_APP.ACESSAR_APP,
    PERMISSOES_APP.ABRIR_OS,
    PERMISSOES_APP.VER_MINHAS_OS,
    PERMISSOES_APP.CANCELAR_PROPRIA_OS,
    PERMISSOES_APP.VER_COMUNICADOS,
    PERMISSOES_APP.VER_NOTIFICACOES,
    PERMISSOES_APP.VER_NOTIFICACOES_PROPRIAS,
    PERMISSOES_APP.VER_PERFIL
  ]),

  [PERFIS_USUARIO.GERENCIA]: Object.freeze([
    PERMISSOES_APP.ACESSAR_APP,
    PERMISSOES_APP.ABRIR_OS,
    PERMISSOES_APP.VER_MINHAS_OS,
    PERMISSOES_APP.VER_TODAS_OS,
    PERMISSOES_APP.CANCELAR_PROPRIA_OS,
    PERMISSOES_APP.VER_COMUNICADOS,
    PERMISSOES_APP.VER_NOTIFICACOES,
    PERMISSOES_APP.VER_NOTIFICACOES_PROPRIAS,
    PERMISSOES_APP.VER_PERFIL,
    PERMISSOES_APP.AUDITAR_HISTORICO,
    PERMISSOES_APP.ALTERAR_PRIORIDADE_OS
  ]),

  [PERFIS_USUARIO.MANUTENCAO]: Object.freeze([
    PERMISSOES_APP.ACESSAR_APP,
    PERMISSOES_APP.ABRIR_OS,
    PERMISSOES_APP.VER_MINHAS_OS,
    PERMISSOES_APP.VER_TODAS_OS,
    PERMISSOES_APP.CANCELAR_PROPRIA_OS,
    PERMISSOES_APP.ASSUMIR_ATENDIMENTO,
    PERMISSOES_APP.ALTERAR_STATUS_OS,
    PERMISSOES_APP.ALTERAR_PRIORIDADE_OS,
    PERMISSOES_APP.FINALIZAR_OS,
    PERMISSOES_APP.VER_PAINEL,
    PERMISSOES_APP.VER_COMUNICADOS,
    PERMISSOES_APP.CRIAR_COMUNICADO,
    PERMISSOES_APP.VER_NOTIFICACOES,
    PERMISSOES_APP.VER_NOTIFICACOES_PROPRIAS,
    PERMISSOES_APP.VER_PERFIL,
    PERMISSOES_APP.VER_ATIVOS,
    PERMISSOES_APP.GERENCIAR_ATIVOS,
    PERMISSOES_APP.VER_PREVENTIVAS,
    PERMISSOES_APP.GERENCIAR_PREVENTIVAS,
    PERMISSOES_APP.VER_DIAGNOSTICO,
    PERMISSOES_APP.GERENCIAR_DIAGNOSTICO,
    PERMISSOES_APP.EXPORTAR_DADOS,
    PERMISSOES_APP.VER_LOGS_TECNICOS,
    PERMISSOES_APP.GERENCIAR_USUARIOS,
    PERMISSOES_APP.AJUSTAR_CONFIGURACOES,
    PERMISSOES_APP.AUDITAR_HISTORICO
  ])
});
